### ISSUE TITLE
Milestone 4 Improvements 

### ISSUE THREAD

**Issue by shaunhutch** [UBC-MDS/drug_consumption_prediction#26]
Shaun
- [x] Contributing Document
- [x] Fix code chunk warnings on report
- [x] report references
- [x] makefile graph

Jenit
- [x] figure captions (eda)
- [x] references(eda)
- [x] purpose(eda)
- [x] move eda from src to doc
- [x] environment.yml

Ritisha
- [x] Add examples to scripts (eg download data)
- [x] analysis directory
- [x] Githubpages Report
- [x] Usage

**Comment by shaunhutch** [comment]
Finished Improvements
