### ISSUE TITLE
Milestone 1 Comments:

### ISSUE THREAD

**Issue by Glenn032787** [UBC-MDS/drug_consumption_prediction#9]
Congratulations on finishing milestone 1! We can see you put a lot of work into this project, nice work! Below we list some specific feedback you can use to improve your project.

We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project. If anything is unclear, please feel free to ask questions in this issue thread.

***1. Project set-up (max 20 points)***
- [ ] Contributing documentation should reflect all the ways people can contribute to the project 
(core members, who should be working in a GitHub flow workflow involving branching in the main project repo and opening PR's, as well as arms-length contributors, who more likely may have to fork the repo before submitting a PR). **-2**
**Comment:**  Core teams contribution workflow is not mentioned.

***2. Project proposal (10 points)***
- [x] The dataset, dataset license and dataset citation should be included in the [README.md](http://readme.md/). **-1**
**Comment:** Missing dataset license
- [x]  The question should be specific enough. For example, “Is eating a healthier diet better for you?” is written ambiguously. What do you mean by “healthier diet”? . Instead, “Does eating at least 5 servings per day of fresh fruits and vegetables lead to fewer upper respiratory tract infections (colds)?” is clearer and more concrete. -1 reasoning
**Comment:** The question is a bit convoluted, I would suggest something like predicting the level of consume of different drugs given their personality traits or predict if a person will have never used a drug

***3. A script that downloads and saves the data***
Great Job!

***4. Exploratory data analysis in a literate code document***
- [ ] There are not figure captions. **-2** **viz**
- [ ] There figure captions for the tables should be above the table. **-1** **viz**
**Comment:** All figures should have captions below and tables should have captions above. See here for [example](https://clauswilke.com/dataviz/visualizing-amounts.html#tab:boxoffice-gross)
- [ ] There is not title, introduction and/or references in the analysis (`.ipynb` or `.Rmd`) file **-2**
**Comment:** Great that you included description for the data in the drug_consumption_data_analysis.ipynb in summary section but I would suggest also including the purpose of this script in the introduction.
- [ ] README should include instructions on how to run the analysis. Clearly specify usage instructions to the point a user could copy and paste them and they would work. 
**Comment:** It is good that you linked to the specific scripts in the usage section. I would also include an example usage for the [download_data.py](http://download_data.py/) including the data URL and file path.

***5. Expectations***
- [ ] Please provide the link to the release as https://github.com/UBC-MDS/REPOSITORY/tree/VERSION

**Comment by brabbit61** [comment]
Hey @Glenn032787, we will work on the items listed above. However, we do have a few clarifications to make:

- Ex 4.1, 4.2: Figure captions have not been mentioned because we have labelled the axes and assigned the plots a title. We also provide a description for the charts / tables.
- Ex 5.1: Yes, we did not use GitHub issues because we communicated via the threads on our pull requests.

I request you to regrade the above questions. 

Also, please find the link to our _Milestone 1_ release below:
https://github.com/UBC-MDS/drug_consumption_prediction/tree/0.0.1

**Comment by Glenn032787** [comment]
Hi,

For 4.1,4.2, as this is suppose to be a report, it is standard practice to include a caption despite having axis title, figure title and description. It can just be a short 1-2 sentence description.

I have given you the marks for 5.1. I have removed it from the issue above.

**Comment by shaunhutch** [comment]
Hi @Glenn032787 ,

Just wondering about part 5:
Please provide the link to the release as https://github.com/UBC-MDS/REPOSITORY/tree/VERSION

Was this an issue with our submission? Just wondering if this is something that can be fixed for Milestone 4?

Thanks!

**Comment by Glenn032787** [comment]
Hi it is standard practice to send the tagged repository to the github repository rather than the download link. This is a very minor formatting issue but it is best practice. 

For example it is standard to practice to send the link as 
https://github.com/UBC-MDS/drug_consumption_prediction/tree/0.0.1 
rather than:
https://github.com/UBC-MDS/drug_consumption_prediction/releases/tag/0.0.1
